# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13SensorService.proto\x12\x0eSensor_service\";\n\nSensorData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\"\x1d\n\x0bStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1a\n\nSensordate\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"\"\n\x0eSensorlocation\x12\x10\n\x08location\x18\x01 \x01(\t\"\x0e\n\x0c\x45mptyMessage\"A\n\x0eSensorDataList\x12/\n\x0bSensor_data\x18\x01 \x03(\x0b\x32\x1a.Sensor_service.SensorData2\xe2\x02\n\rSensorService\x12I\n\x0c\x43reateSensor\x12\x1a.Sensor_service.SensorData\x1a\x1b.Sensor_service.StatusReply\"\x00\x12U\n\x15GetSensorDataFromdate\x12\x1a.Sensor_service.Sensordate\x1a\x1e.Sensor_service.SensorDataList\"\x00\x12]\n\x19GetSensorDataFromlocation\x12\x1e.Sensor_service.Sensorlocation\x1a\x1e.Sensor_service.SensorDataList\"\x00\x12P\n\x0eListAllSensors\x12\x1c.Sensor_service.EmptyMessage\x1a\x1e.Sensor_service.SensorDataList\"\x00\x42\x37\n\x1bio.grpc.examples.iotserviceB\x0fIoTServiceProtoP\x01\xa2\x02\x04TEMPb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SensorService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.iotserviceB\017IoTServiceProtoP\001\242\002\004TEMP'
  _SENSORDATA._serialized_start=39
  _SENSORDATA._serialized_end=98
  _STATUSREPLY._serialized_start=100
  _STATUSREPLY._serialized_end=129
  _SENSORDATE._serialized_start=131
  _SENSORDATE._serialized_end=157
  _SENSORLOCATION._serialized_start=159
  _SENSORLOCATION._serialized_end=193
  _EMPTYMESSAGE._serialized_start=195
  _EMPTYMESSAGE._serialized_end=209
  _SENSORDATALIST._serialized_start=211
  _SENSORDATALIST._serialized_end=276
  _SENSORSERVICE._serialized_start=279
  _SENSORSERVICE._serialized_end=633
# @@protoc_insertion_point(module_scope)
